// Generated by scripts/weekly-game/build-camera-host.mjs from reviewed, mirrored
// hand-package-v2 packages: package SHA-256 → reviewed script SHA-256 and sandbox host.
export const CAMERA_HOSTS={
    "07f697bf8d256739aea52c94aacc0aa6ed25bf1356321952194bfc82bd822ca2": {
        "script": "9ccfccc385ead75051bb031f16db423d056d354c21ab6abb98cb3e082806df31",
        "host": "/assets/weekly-game/camera/fadcde7a874856259743/index.html"
    }
};
