import {build} from 'esbuild';
import {writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const result = await build({entryPoints:['scripts/weekly-game/tracker-worker.js'],bundle:true,format:'iife',platform:'browser',target:'es2020',minify:true,legalComments:'none',write:false});
const bytes = result.outputFiles[0].contents;
const name = `tracker-${createHash('sha256').update(bytes).digest('hex').slice(0,20)}.js`;
await writeFile(`assets/weekly-game/${name}`,bytes);
await writeFile('app/weekly-game/tracker-asset.js',`// Generated by scripts/weekly-game/build-tracker.mjs.\nexport const TRACKER_URL = '/assets/weekly-game/${name}';\n`);
console.log(name);
